name: Trigger

on:
  push:
    branches: [ main ]

jobs:
  trigger-main-workflow:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: cURL
        run: ./api-trigger.sh
