# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run Dockerfile
        run: docker build .

  # Bash script with env
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          HELLO: "hello"
          WORLD: "world"
        run: ./script.sh

  # Job needs earlier job
  # Uses secret from GitHub repository
  uses-secret:
    needs: script
    runs-on: macos-11.0
    steps:
      - name: secret
        uses: actions/checkout@v2
      - name: run secret
        env:
          SUPER_SECRET: ${{ secrets.SECRET }}
        run: ./secret.sh "$SUPER_SECRET" > output.txt
      - name: artifact
        uses: actions/upload-artifact@v1
        with:
          name: secret-output
          path: output.txt

  # Windows executes some npm/node
  npm-node-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm --version
      - run: node --version

  # Sharing data between jobs
  sharing-data:
    runs-on: ubuntu-latest
    needs: uses-secret
    steps:
      - name: sharing-data
        uses: actions/download-artifact@v2
        with:
          name: secret-output
      - name: cat shared data
        shell: bash
        run: cat output.txt

  # Using default ENV variables
  default-env:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "$GITHUB_ACTOR started this script"
          echo "$HOME is my home"
          echo "$GITHUB_REPOSITORY is the repository name"
          echo "$GITHUB_REF is the branch that triggered the workflow"
